-- Таблица рейтингов MPA
CREATE TABLE IF NOT EXISTS mpa_rating
(
    mpa_id      INTEGER PRIMARY KEY,
    name        VARCHAR(10) NOT NULL UNIQUE,
    description VARCHAR(255)
);

-- Таблица жанров
CREATE TABLE IF NOT EXISTS genres
(
    genre_id INTEGER PRIMARY KEY,
    name     VARCHAR(50) NOT NULL UNIQUE
);

-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users
(
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    login    VARCHAR(255) NOT NULL UNIQUE,
    name     VARCHAR(255),
    birthday DATE
);

-- Таблица фильмов
CREATE TABLE IF NOT EXISTS films
(
    film_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(500),
    release_date DATE,
    duration     INTEGER,
    mpa_id       INTEGER REFERENCES mpa_rating (mpa_id)
);

-- Таблица связи фильмов и жанров
CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genres (genre_id),
    PRIMARY KEY (film_id, genre_id)
);

-- Таблица лайков фильмов
CREATE TABLE IF NOT EXISTS film_likes
(
    film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

-- Таблица дружбы
CREATE TABLE IF NOT EXISTS friendship
(
    user_id   INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    status    VARCHAR(20) NOT NULL,
    PRIMARY KEY (user_id, friend_id)
);

-- Таблица отзывов
CREATE TABLE IF NOT EXISTS reviews
(
    review_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content     VARCHAR(1000) NOT NULL,
    is_positive BOOLEAN       NOT NULL,
    user_id     INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    film_id     INTEGER REFERENCES films (film_id) ON DELETE CASCADE
);

-- Таблица оценок отзывов (лайки/дизлайки)
CREATE TABLE IF NOT EXISTS review_ratings
(
    review_id INTEGER REFERENCES reviews (review_id) ON DELETE CASCADE,
    user_id   INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    is_like   BOOLEAN NOT NULL,
    PRIMARY KEY (review_id, user_id)
);

-- Таблица ленты пользователя
CREATE TABLE IF NOT EXISTS feed
(
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    entity_id INTEGER NOT NULL,
    event_type VARCHAR(20) NOT NULL,
    operation VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Индексы для оптимизации запросов
-- Отзывы
CREATE INDEX IF NOT EXISTS idx_reviews_film_id ON reviews (film_id);
CREATE INDEX IF NOT EXISTS idx_review_ratings_review_id ON review_ratings (review_id);
-- Лента
CREATE INDEX IF NOT EXISTS idx_feed_user_id ON feed (user_id);
